### PR TITLE
Python 3 support (Work In Progress)

### PR DESCRIPTION
**Pull request by Xaroth**
Right, it's a big one, and there are some caveats:

1) It adds a new requirements to the 'requests' package.. commit b84a2c1 will show you how it simplifies most of the http calls.. it's a great library and commonly used, so I assumed the added requirement would be that bad.

2) The soudnmanager, for me, on windows, causes a segfault thus crashing the entire app during startup.. now from what I see I'm not sure if pyglet is the best of choices for playing audio, but since I'm not that familiar with audio frameworks, I'll leave it for now while I try to figure out what's wrong and how to fix it.

3) I have not (yet) tested compatibility with py2, I think I covered most cases, but I thought to get the PR in early so people could review and test it on other platforms.

4) Import rules have been rewritten to be in-line with python3' new rules:
`import evegate`
assumes you are importing a package called evegate, where:
`from . import evegate`
imports it from the current package/module directory.
This change is backwards compatible with python 2.6 and onwards.

I personally tested it (with sound disabled) on python 3.5 (x64) on windows...  he other fixes and things I'm

### CODE REVIEW

**Comment by Xanthos-Eve** [comment]
Good set of changes. FileWatcher changes especially - the app spends a lot of time there. Approved!

**Comment by Xanthos-Eve** [comment]
Please feel free to recommend an alternate sound library. Pygame seem like a good one though I had problems installing it on my Mac so I opted for Piglet instead.

**Comment by Xaroth** [comment]
I will poke around a bit; but please keep in mind that this needs to be thoroughly tested as, as it stands, there are crashes on py3  due to sound..

**Comment by Xaroth** [comment]
Did some further tracing; the error occurs on line 149 of the soundmanager, where the media is loaded... as far as I can see the media file exists and it's very much readable, so it might be an issue with pyglet, or that I'm using a 64 bit build.. not sure yet.

**Pull request merged**
